export const UPLOAD_FULL_PAPER_FILE = "app/FullPaperUpload/UPLOAD_FULL_PAPER_FILE";
export const UPLOAD_FULL_PAPER_FILE_SUCCESS = "app/FullPaperUpload/UPLOAD_FULL_PAPER_FILE_SUCCESS";
export const UPLOAD_FULL_PAPER_FILE_FAILURE = "app/FullPaperUpload/UPLOAD_FULL_PAPER_FILE_FAILURE";

export const FULL_PAPER_DATA = "app/FullPaperUpload/FULL_PAPER_DATA";
export const FULL_PAPER_DATA_SUCCESS = "app/FullPaperUpload/FULL_PAPER_DATA_SUCCESS";
export const FULL_PAPER_DATA_FAILURE = "app/FullPaperUpload/FULL_PAPER_DATA_FAILURE";

export const RESET_FULL_PAPER_DATA_SUCCESS_TO_INITIAL_STATE ="app/FullPaperUpload/RESET_FULL_PAPER_DATA_SUCCESS_TO_INITIAL_STATE"