export const SEND_SPONSOR_USER = "app/SEND_SPONSOR_USER_SUCCESS/SEND_SPONSOR_USER";
export const SEND_SPONSOR_USER_SUCCESS = "app/cz/SEND_SPONSOR_USER_SUCCESS";
export const SEND_SPONSOR_USER_FAILURE = "app/SEND_SPONSOR_USER_SUCCESS/SEND_SPONSOR_USER_FAILURE";