export const GET_USER_TRANSACTION_LIST = "app/TransactionList/GET_USER_TRANSACTION_LIST";
export const GET_USER_TRANSACTION_LIST_SUCCESS = "app/TransactionList/GET_USER_TRANSACTION_LIST_SUCCESS";
export const GET_USER_TRANSACTION_LIST_FAILURE = "app/TransactionList/GET_USER_TRANSACTION_LIST_FAILURE";