export const USER_ABSTRACT_LIST = "app/GetUserAbstractList/USER_ABSTRACT_LIST"
export const USER_ABSTRACT_LIST_SUCCESS = "app/GetUserAbstractList/USER_ABSTRACT_LIST_SUCCESS"
export const USER_ABSTRACT_LIST_FAILURE = "app/GetUserAbstractList/USER_ABSTRACT_LIST_FAILURE"

