export const GET_USER_ABSTRACT_PAPER = "app/previewPaper/GET_USER_ABSTRACT_PAPER";
export const GET_USER_ABSTRACT_PAPER_SUCCESS = "app/previewPaper/GET_USER_ABSTRACT_PAPER_SUCCESS";
export const GET_USER_ABSTRACT_PAPER_FAILURE = "app/previewPaper/GET_USER_ABSTRACT_PAPER_FAILURE";