export const GET_USER_DATA_FOR_ATTENDANCE = "app/UserAttendance/GET_USER_DATA_FOR_ATTENDANCE";
export const GET_USER_DATA_FOR_ATTENDANCE_SUCCESS = "app/UserAttendance/GET_USER_DATA_FOR_ATTENDANCE_SUCCESS";
export const GET_USER_DATA_FOR_ATTENDANCE_FAILURE = "app/UserAttendance/GET_USER_DATA_FOR_ATTENDANCE_FAILURE";

export const MARK_USER_ATTENDANCE = "app/UserAttendance/MARK_USER_ATTENDANCE";
export const MARK_USER_ATTENDANCE_SUCCESS = "app/UserAttendance/MARK_USER_ATTENDANCE_SUCCESS";
export const MARK_USER_ATTENDANCE_FAILURE = "app/UserAttendance/MARK_USER_ATTENDANCE_FAILURE";