export const USER_TRANSACTION_DETAILS = "app/TransactionDetails/USER_TRANSACTION_DETAILS";
export const USER_TRANSACTION_DETAILS_SUCCESS = "app/TransactionDetails/USER_TRANSACTION_DETAILS_SUCCESS";
export const USER_TRANSACTION_DETAILS_FAILURE = "app/TransactionDetails/USER_TRANSACTION_DETAILS_FAILURE";

