export const SAVE_REGISTER_USER_DATA = "app/Create/SAVE_REGISTER_USER_DATA";
export const SAVE_REGISTER_USER_DATA_SUCCESS = "app/Create/SAVE_REGISTER_USER_DATA_SUCCESS";
export const SAVE_REGISTER_USER_DATA_FAILURE = "app/Create/SAVE_REGISTER_USER_DATA_FAILURE";

export const RESET_TO_INITIAL_STATE = "app/Create/RESET_TO_INITIAL_STATE";

export const GET_LOGGEDID_USER = "app/Create/GET_LOGGEDID_USER";
export const GET_LOGGEDID_USER_SUCCESS = "app/Create/GET_LOGGEDID_USER_SUCCESS";
export const GET_LOGGEDID_USER_FAILURE = "app/Create/GET_LOGGEDID_USER_FAILURE";

export const UPDATE_REGISTERED_USER = "app/Update/UPDATE_REGISTERED_USER";
export const UPDATE_REGISTERED_USER_SUCCESS = "app/Update/UPDATE_REGISTERED_USER_SUCCESS";
export const UPDATE_REGISTERED_USER_FAILURE = "app/Update/UPDATE_REGISTERED_USER_FAILURE";

