export const SAVE_REGISTER_USER_DATA = "app/Create/SAVE_REGISTER_USER_DATA";
export const SAVE_REGISTER_USER_DATA_SUCCESS = "app/Create/SAVE_REGISTER_USER_DATA_SUCCESS";
export const SAVE_REGISTER_USER_DATA_FAILURE = "app/Create/SAVE_REGISTER_USER_DATA_FAILURE";

export const RESET_TO_INITIAL_STATE = "app/Create/RESET_TO_INITIAL_STATE";