export const GET_FULL_PAPER_LIST = "app/FullPaperPage/GET_FULL_PAPER_LIST"
export const GET_FULL_PAPER_LIST_SUCCESS = "app/FullPaperPage/GET_FULL_PAPER_LIST_SUCCESS"
export const GET_FULL_PAPER_LIST_FAILURE = "app/FullPaperPage/GET_FULL_PAPER_LIST_FAILURE"

export const GET_USER_FULL_PAPER_LIST = "app/FullPaperPage/GET_USER_FULL_PAPER_LIST"
export const GET_USER_FULL_PAPER_LIST_SUCCESS = "app/FullPaperPage/GET_USER_FULL_PAPER_LIST_SUCCESS"
export const GET_USER_FULL_PAPER_LIST_FAILURE = "app/FullPaperPage/GET_USER_FULL_PAPER_LIST_FAILURE"